export enum StoreActionType {
  SET_SEARCH_STR = 'SET_SEARCH_STR',
  SET_PROJECTS = 'SET_SEARCH_RESULT',
  SET_SEARCH_LOADING = 'SET_SEARCH_LOADING',
  SET_BASE_URL = 'SET_BASE_URL',
  SEARCH = 'SEARCH',
}